apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: busybox
  name: busybox-cc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: busybox
  template:
    metadata:
      labels:
        app: busybox
    spec:
      runtimeClassName: kata-remote
      containers:
      - image: ghcr.io/mkulke/busybox-encrypted:oss23-demo
        name: busybox
        command: ["sleep", "infinity"]
